### ISSUE TITLE
analytics.muni.org not anonymizing visitor IP addresses

### ISSUE THREAD

**Issue by konklone** [MunicipalityOfAnchorage/analytics.muni.org#14]
The site maintains the language we use at https://analytics.usa.gov:

> This program does not track individuals, and [anonymizes the IP addresses](https://support.google.com/analytics/answer/2763052?hl=en) of visitors.

However, it looks like in the process of adapting the analytics.usa.gov code, you removed these two lines from the Google Analytics reporting snippet:

```
    ga('set', 'anonymizeIp', true);
    ga('set', 'forceSSL', true);
```

The `forceSSL` line is actually not necessary anymore, now that Google Analytics finally [encrypts all connections](https://support.google.com/analytics/answer/6385009), but the `anonymizeIP` line is necessary in order to [anonymize IP addresses](https://support.google.com/analytics/answer/2763052?hl=en).

**Comment by jdeanfranklin** [comment]
Thanks for catching that. I've added those lines back to the reporting snippet.
